# Generated by Django 4.1.3 on 2022-12-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
